name: build

on: [pull_request, push]

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up APT packages
        run: sudo apt-get install -y libopenal-dev libopus-dev libasound2-dev ffmpeg
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.15.x
          targets: "*/arm"
          v: true
          ldflags: -s -w
      - run: ls -R ./build
