name: build

on: [pull_request, push]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - name: Set up APT packages
        run: sudo apt-get install -y gcc-arm* libopenal-dev libopus-dev libasound2-dev ffmpeg
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 5
          CGO_ENABLED: 1
          CC: arm-linux-gnu-gcc
        run: go build
