name: build

on: [pull_request, push]

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up APT packages
        run:  sudo apt-get install libopenal1 libopenal-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.15.x
          targets: windows/amd64,linux/amd64,darwin/amd64,*/arm
          v: true
          ldflags: -s -w
      - run: ls -R ./build
